services:
  postgres: 
    image: postgres:16
    container_name: fastapi_db
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_db
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U fastapi']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
